### ISSUE TITLE
[JENKINS-68254] Jenkins build queue is cleared after restart (regression in 2.333)

### ISSUE THREAD

**Issue by lemeurherve** [lemeurherve-org/demo#849]
<p>After a Jenkins update from 2.319.3 LTS to 2.332.2 LTS we have noticed that when shutting down the Jenkins docker container the build queue is no longer preserved and all scheduled builds are lost when starting Jenkins again. When rolling back to 2.319.3 it is working again as expected.</p>

<p>Observed behavior:</p>
<ul class="alternate" type="square">
	<li>Jenkins build queue (/var/jenkins_home/queue.xml) is cleared when shutting down the jenkins container</li>
</ul>

<p>Expected behavior:</p>
<ul class="alternate" type="square">
	<li>Jenkins build queue is preserved in /var/jenkins_home/queue.xml when shutting down the jenkins container and loaded at the next Jenkins startup</li>
</ul>

<p> </p>

<p>#########<br/>
 #Steps to reproduce<br/>
 #########</p>

<p>1. Run the Jenkins docker container with tag 2.332.2-lts-jdk11</p>

<pre>
docker run -d --name jenkins -p 8080:8080 -p 50000:50000 --restart always -v jenkins_home:/<span class="code-keyword">var</span>/jenkins_home jenkins/jenkins:2.332.2-lts-jdk11</pre>
<p> </p>

<p>2. Install the "Schedule Build" plugin</p>

<p>3. Create a simple testjob</p>

<p>4. Navigate to the created testjob. Press the "Schedule Build" button. Then enter a time and date which is in the future (i.e. in 1 hour) and press "Schedule". You will see a job in the build queue waiting to be executed at the time you have entered before.<br/>
 <span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/57673/57673_image-2022-04-12-17-21-39-066.png" height="433" width="308" style="border: 0px solid black" /></span><span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/57674/57674_image-2022-04-12-17-32-12-621.png" height="419" width="276" style="border: 0px solid black" /></span></p>

<p>5. Monitor the file /var/jenkins_home/queue.xml wherever you have mounted the volume outside the container. The queue.xml isn't created immediately, but should be created within a minute after the job has been scheduled and has the information of your scheduled build.</p>

<pre>
<?xml version=<span class="code-quote">'1.1'</span> encoding=<span class="code-quote">'UTF-8'</span>?>
<hudson.model.Queue_-State>
  <counter>18</counter>
  <items>
    <hudson.model.Queue_-WaitingItem>
      <actions>
<hudson.model.CauseAction>
  <causeBag class=<span class="code-quote">"linked-hash-map"</span>>
    <entry>
      <hudson.model.Cause_-UserIdCause>
<userId>admin</userId>
      </hudson.model.Cause_-UserIdCause>
      <<span class="code-object">int</span>>1</<span class="code-object">int</span>>
    </entry>
  </causeBag>
</hudson.model.CauseAction>
      </actions>
      <id>18</id>
      <task class=<span class="code-quote">"hudson.model.FreeStyleProject"</span>>testjob</task>
      <inQueueSince>1649775922437</inQueueSince>
      <timestamp>
<time>1649800801433</time>
<timezone>Etc/UTC</timezone>
      </timestamp>
    </hudson.model.Queue_-WaitingItem>
  </items> </pre>
<p>6. Stop the Jenkins container</p>

<pre>
docker stop jenkins</pre>
<p>7. Monitor /var/jenkins_home/queue.xml in your volume mount again. The file has been altered, and the information for the scheduled job inside the xml structure is gone</p>

<pre>
<?xml version=<span class="code-quote">'1.1'</span> encoding=<span class="code-quote">'UTF-8'</span>?>
<hudson.model.Queue_-State>
  <counter>18</counter>
  <items/>
</hudson.model.Queue_-State></pre>
<p>8. Start the Jenkins container</p>

<pre>
docker start jenkins</pre>
<p>9. Jenkins Build queue is empty</p>

<p> </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=chri4774">chri4774</a>, imported from: <a href="https://issues.jenkins.io/browse/JENKINS-68254" target="_blank">Jenkins build queue is cleared after restart (regression in 2.333)</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=basil">basil</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2022-04-12T20:49:57+02:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 3
<li><b>imported</b>: 2025-11-14
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After a Jenkins update from 2.319.3 LTS to 2.332.2 LTS we have noticed that when shutting down the Jenkins docker container the build queue is no longer preserved and all scheduled builds are lost when starting Jenkins again. When rolling back to 2.319.3 it is working again as expected.</p>

<p>Observed behavior:</p>
<ul class="alternate" type="square">
	<li>Jenkins build queue (/var/jenkins_home/queue.xml) is cleared when shutting down the jenkins container</li>
</ul>

<p>Expected behavior:</p>
<ul class="alternate" type="square">
	<li>Jenkins build queue is preserved in /var/jenkins_home/queue.xml when shutting down the jenkins container and loaded at the next Jenkins startup</li>
</ul>

<p> </p>

<p>#########
 #Steps to reproduce
 #########</p>

<p>1. Run the Jenkins docker container with tag 2.332.2-lts-jdk11</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">docker run -d --name jenkins -p 8080:8080 -p 50000:50000 --restart always -v jenkins_home:/<span class="code-keyword">var</span>/jenkins_home jenkins/jenkins:2.332.2-lts-jdk11</pre>
</div></div>
<p> </p>

<p>2. Install the "Schedule Build" plugin</p>

<p>3. Create a simple testjob</p>

<p>4. Navigate to the created testjob. Press the "Schedule Build" button. Then enter a time and date which is in the future (i.e. in 1 hour) and press "Schedule". You will see a job in the build queue waiting to be executed at the time you have entered before.
 <span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/57673/57673_image-2022-04-12-17-21-39-066.png" height="433" width="308" style="border: 0px solid black" /></span><span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/57674/57674_image-2022-04-12-17-32-12-621.png" height="419" width="276" style="border: 0px solid black" /></span></p>

<p>5. Monitor the file /var/jenkins_home/queue.xml wherever you have mounted the volume outside the container. The queue.xml isn't created immediately, but should be created within a minute after the job has been scheduled and has the information of your scheduled build.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">&lt;?xml version=<span class="code-quote">'1.1'</span> encoding=<span class="code-quote">'UTF-8'</span>?&gt;
&lt;hudson.model.Queue_-State&gt;
  &lt;counter&gt;18&lt;/counter&gt;
  &lt;items&gt;
    &lt;hudson.model.Queue_-WaitingItem&gt;
      &lt;actions&gt;
        &lt;hudson.model.CauseAction&gt;
          &lt;causeBag class=<span class="code-quote">"linked-hash-map"</span>&gt;
            &lt;entry&gt;
              &lt;hudson.model.Cause_-UserIdCause&gt;
                &lt;userId&gt;admin&lt;/userId&gt;
              &lt;/hudson.model.Cause_-UserIdCause&gt;
              &lt;<span class="code-object">int</span>&gt;1&lt;/<span class="code-object">int</span>&gt;
            &lt;/entry&gt;
          &lt;/causeBag&gt;
        &lt;/hudson.model.CauseAction&gt;
      &lt;/actions&gt;
      &lt;id&gt;18&lt;/id&gt;
      &lt;task class=<span class="code-quote">"hudson.model.FreeStyleProject"</span>&gt;testjob&lt;/task&gt;
      &lt;inQueueSince&gt;1649775922437&lt;/inQueueSince&gt;
      &lt;timestamp&gt;
        &lt;time&gt;1649800801433&lt;/time&gt;
        &lt;timezone&gt;Etc/UTC&lt;/timezone&gt;
      &lt;/timestamp&gt;
    &lt;/hudson.model.Queue_-WaitingItem&gt;
  &lt;/items&gt; </pre>
</div></div>
<p>6. Stop the Jenkins container</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">docker stop jenkins</pre>
</div></div>
<p>7. Monitor /var/jenkins_home/queue.xml in your volume mount again. The file has been altered, and the information for the scheduled job inside the xml structure is gone</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">&lt;?xml version=<span class="code-quote">'1.1'</span> encoding=<span class="code-quote">'UTF-8'</span>?&gt;
&lt;hudson.model.Queue_-State&gt;
  &lt;counter&gt;18&lt;/counter&gt;
  &lt;items/&gt;
&lt;/hudson.model.Queue_-State&gt;</pre>
</div></div>
<p>8. Start the Jenkins container</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">docker start jenkins</pre>
</div></div>
<p>9. Jenkins Build queue is empty</p>

<p> </p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Jenkins 2.332.2 LTS JDK11</code></li></ul>
<details><summary><i>2 attachments</i></summary>

- [image-2022-04-12-17-21-39-066.png](https://issues.jenkins.io/secure/attachment/57673/image-2022-04-12-17-21-39-066.png)
  > ![image-2022-04-12-17-21-39-066.png](https://issues.jenkins.io/secure/attachment/57673/image-2022-04-12-17-21-39-066.png)
- [image-2022-04-12-17-32-12-621.png](https://issues.jenkins.io/secure/attachment/57674/image-2022-04-12-17-32-12-621.png)
  > ![image-2022-04-12-17-32-12-621.png](https://issues.jenkins.io/secure/attachment/57674/image-2022-04-12-17-32-12-621.png)
</details>

**Comment by lemeurherve** [comment]
<details><summary><i>basil's <a href="https://issues.jenkins.io/browse/JENKINS-68254?focusedId=424411&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-424411">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>You have not provided enough information for others to be able to help you. I followed your instructions to the letter, and at Step 4 ("Schedule a build for the testjob") my build completed without creating a <tt>queue.xml</tt> file.</p>

<p>Provide detailed instructions to reproduce the problem <em>from scratch</em>.</p>
</pre>
</details>

</details>
<p>You have not provided enough information for others to be able to help you. I followed your instructions to the letter, and at Step 4 ("Schedule a build for the testjob") my build completed without creating a <tt>queue.xml</tt> file.</p>

<p>Provide detailed instructions to reproduce the problem <em>from scratch</em>.</p>

**Comment by lemeurherve** [comment]
<details><summary><i>chri4774's <a href="https://issues.jenkins.io/browse/JENKINS-68254?focusedId=424416&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-424416">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=basil" class="user-hover" rel="basil">Basil Crow</a> I've updated the description for Step 4. The job needs to be in the queue and waiting to be executed. I hope it's more clear now.</p>
</pre>
</details>

</details>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=basil" class="user-hover" rel="basil">Basil Crow</a> I've updated the description for Step 4. The job needs to be in the queue and waiting to be executed. I hope it's more clear now.</p>

**Comment by lemeurherve** [comment]
<details><summary><i>basil's <a href="https://issues.jenkins.io/browse/JENKINS-68254?focusedId=424428&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-424428">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>I followed your instructions to the letter, but I cannot reproduce this problem. At step 7, I see the correct queue with the job still enqueued. And we also have an integration test that covers this scenario, which is passing. I have no idea what is going wrong on your setup.</p>

<p>If you can reproduce this reliably, check to see if the problem occurs on the latest weekly. And if it doesn't, try cherry-picking commit a6fa7b3abd onto jenkins-2.332.2 and see if that commit makes a difference.</p>
</pre>
</details>

</details>
<p>I followed your instructions to the letter, but I cannot reproduce this problem. At step 7, I see the correct queue with the job still enqueued. And we also have an integration test that covers this scenario, which is passing. I have no idea what is going wrong on your setup.</p>

<p>If you can reproduce this reliably, check to see if the problem occurs on the latest weekly. And if it doesn't, try cherry-picking commit a6fa7b3abd onto jenkins-2.332.2 and see if that commit makes a difference.</p>

**Comment by lemeurherve** [comment]
<details><summary><i>basil's <a href="https://issues.jenkins.io/browse/JENKINS-68254?focusedId=424431&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-424431">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>After adding this debug code</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>diff --git a/core/src/main/java/hudson/model/Queue.java b/core/src/main/java/hudson/model/Queue.java
index e0abed68cc..b937cfc231 100644
--- a/core/src/main/java/hudson/model/Queue.java
+++ b/core/src/main/java/hudson/model/Queue.java
@@ -465,10 +465,14 @@ public class Queue extends ResourceController implements Saveable {
                 if (item.task instanceof TransientTask)  continue;
                 state.items.add(item);
             }
+            if (state.items.isEmpty()) {
+                new Throwable("Saving empty queue!").printStackTrace(System.err);
+            }
</pre>
</div></div>

<p>I am able to see the problem:</p>

<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>2022-04-12 18:37:56.887+0000 [id=26]    INFO    winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
java.lang.Throwable: Saving empty queue!
        at hudson.model.Queue.save(Queue.java:469)
        at jenkins.model.Jenkins._cleanUpPersistQueue(Jenkins.java:3835)
        at jenkins.model.Jenkins.cleanUp(Jenkins.java:3590)
        at hudson.lifecycle.Lifecycle.lambda$new$0(Lifecycle.java:63)
        at java.base/java.lang.Thread.run(Thread.java:829)
</pre>
</div></div>

<p>This stack trace is coming from our cleanup handler, not Winstone's. Our cleanup handler is running at the wrong point in the lifecycle and is saving an empty queue.</p>

<p>This bug was introduced in commit 1a42044347 (<a href="https://github.com/jenkinsci/jenkins/pull/6230" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/6230</a>) in Jenkins 2.333. It was reverted in commit a6fa7b3abd (<a href="https://github.com/jenkinsci/jenkins/pull/6454" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/6454</a>) in 2.343. I verified that after cherry-picking commit a6fa7b3abd onto jenkins-2.332.2 that I could no longer reproduce the problem. Therefore I am marking this bug as resolved.</p>

<p>Unfortunately the offending commit 1a42044347 was cherry-picked onto stable-2.332 as commit 3097bb612a and is present in 2.332.1 and 2.332.2. Therefore I have added the lts-candidate label to this PR in order to request that commit a6fa7b3abd be backported to stable-2.332 and released in 2.332.3.</p>
</pre>
</details>

</details>
<p>After adding this debug code</p>



```
diff --git a/core/src/main/java/hudson/model/Queue.java b/core/src/main/java/hudson/model/Queue.java
index e0abed68cc..b937cfc231 100644
--- a/core/src/main/java/hudson/model/Queue.java
+++ b/core/src/main/java/hudson/model/Queue.java
@@ -465,10 +465,14 @@ public class Queue extends ResourceController implements Saveable {
 if (item.task instanceof TransientTask)  continue;
 state.items.add(item);
     }
+    if (state.items.isEmpty()) {
+new Throwable("Saving empty queue!").printStackTrace(System.err);
+    }
```

<p>I am able to see the problem:</p>



```
2022-04-12 18:37:56.887+0000 [id=26]    INFO    winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
java.lang.Throwable: Saving empty queue!
at hudson.model.Queue.save(Queue.java:469)
at jenkins.model.Jenkins._cleanUpPersistQueue(Jenkins.java:3835)
at jenkins.model.Jenkins.cleanUp(Jenkins.java:3590)
at hudson.lifecycle.Lifecycle.lambda$new$0(Lifecycle.java:63)
at java.base/java.lang.Thread.run(Thread.java:829)
```

<p>This stack trace is coming from our cleanup handler, not Winstone's. Our cleanup handler is running at the wrong point in the lifecycle and is saving an empty queue.</p>

<p>This bug was introduced in commit 1a42044347 (<a href="https://github.com/jenkinsci/jenkins/pull/6230" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/6230</a>) in Jenkins 2.333. It was reverted in commit a6fa7b3abd (<a href="https://github.com/jenkinsci/jenkins/pull/6454" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/6454</a>) in 2.343. I verified that after cherry-picking commit a6fa7b3abd onto jenkins-2.332.2 that I could no longer reproduce the problem. Therefore I am marking this bug as resolved.</p>

<p>Unfortunately the offending commit 1a42044347 was cherry-picked onto stable-2.332 as commit 3097bb612a and is present in 2.332.1 and 2.332.2. Therefore I have added the lts-candidate label to this PR in order to request that commit a6fa7b3abd be backported to stable-2.332 and released in 2.332.3.</p>

**Comment by lemeurherve** [comment]
<details><summary><i>basil's <a href="https://issues.jenkins.io/browse/JENKINS-68254?focusedId=424433&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-424433">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>To summarize, the problem exists in 2.333 through 2.342 inclusive as well as 2.332.1 and 2.332.2. We will need verification prior to backporting this to 2.332.3. <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=chri4774" class="user-hover" rel="chri4774">Christian Stoff</a> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=reinholdfuereder" class="user-hover" rel="reinholdfuereder">Reinhold Füreder</a> Would you be able to verify the fix? You can do this by upgrading to 2.343, or else cherry-picking commit a6fa7b3abd onto <tt>stable-2.332</tt> and upgrading to the resulting WAR. Either way, confirmation that <a href="https://github.com/jenkinsci/jenkins/pull/6454" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/6454</a> resolved the issue will help facilitate the backport to 2.332.3. Thanks!</p>
</pre>
</details>

</details>
<p>To summarize, the problem exists in 2.333 through 2.342 inclusive as well as 2.332.1 and 2.332.2. We will need verification prior to backporting this to 2.332.3. <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=chri4774" class="user-hover" rel="chri4774">Christian Stoff</a> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=reinholdfuereder" class="user-hover" rel="reinholdfuereder">Reinhold Füreder</a> Would you be able to verify the fix? You can do this by upgrading to 2.343, or else cherry-picking commit a6fa7b3abd onto <tt>stable-2.332</tt> and upgrading to the resulting WAR. Either way, confirmation that <a href="https://github.com/jenkinsci/jenkins/pull/6454" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/jenkins/pull/6454</a> resolved the issue will help facilitate the backport to 2.332.3. Thanks!</p>

**Comment by lemeurherve** [comment]
<details><summary><i>chri4774's <a href="https://issues.jenkins.io/browse/JENKINS-68254?focusedId=424456&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-424456">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=basil" class="user-hover" rel="basil">Basil Crow</a> thanks for the fast response! I've just tested it with the jenkins/jenkins:2.343-jdk11 docker image and can confirm that this new version fixed the issue. <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>
</pre>
</details>

</details>
<p><a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=basil" class="user-hover" rel="basil">Basil Crow</a> thanks for the fast response! I've just tested it with the jenkins/jenkins:2.343-jdk11 docker image and can confirm that this new version fixed the issue. <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

**Comment by lemeurherve** [comment]
<details><summary><i>basil's <a href="https://issues.jenkins.io/browse/JENKINS-68254?focusedId=424486&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-424486">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>Thanks <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=chri4774" class="user-hover" rel="chri4774">Christian Stoff</a> for confirming that the issue has been resolved.</p>
</pre>
</details>

</details>
<p>Thanks <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=chri4774" class="user-hover" rel="chri4774">Christian Stoff</a> for confirming that the issue has been resolved.</p>

**Comment by lemeurherve** [comment]
<details><summary><i>basil's <a href="https://issues.jenkins.io/browse/JENKINS-68254?focusedId=424488&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-424488">comment</a>:</i></summary>


<details><summary><sub><i>Raw content of original comment:</i></sub></summary>

<pre>
<p>This fix should be present in the forthcoming 2.332.3 release candidate, but for anyone who wants to try a preview, this incremental is available:</p>

<p><a href="https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/main/jenkins-war/2.332.3-rc32044.d35b_42c4e6e3/" class="external-link" target="_blank" rel="nofollow noopener">https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/main/jenkins-war/2.332.3-rc32044.d35b_42c4e6e3/</a></p>
</pre>
</details>

</details>
<p>This fix should be present in the forthcoming 2.332.3 release candidate, but for anyone who wants to try a preview, this incremental is available:</p>

<p><a href="https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/main/jenkins-war/2.332.3-rc32044.d35b_42c4e6e3/" class="external-link" target="_blank" rel="nofollow noopener">https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/main/jenkins-war/2.332.3-rc32044.d35b_42c4e6e3/</a></p>

**Comment by lemeurherve** [comment]
<i>[Originally duplicated by: <a href="https://github.com/lemeurherve-org/demo/issues?q=in%3Atitle%20JENKINS-68255">JENKINS-68255</a>]</i>

**Comment by lemeurherve** [comment]
<i>[Originally duplicated by: <a href="https://github.com/lemeurherve-org/demo/issues?q=in%3Atitle%20JENKINS-68224">JENKINS-68224</a>]</i>
